name: cryptography
version: 0.1.2
author: Gohilla team <opensource@gohilla.com>
homepage: https://github.com/gohilla/cryptography.dart
description:
  Cryptographic algorithms implemented in Dart. Includes Chacha20, X25519 (Curve25519), and others.

environment:
  sdk: '>=2.5.0 <3.0.0'

dependencies:
  collection: ^1.14.0
  crypto: ^2.1.3
  meta: ^1.1.0

dev_dependencies:
  benchmark_harness: ^1.0.0
  pedantic: ^1.8.0
  raw: any
  test: ^1.6.0
