name: chacha20
version: 2.0.0
author: Gohilla team <opensource@gohilla.com>
homepage: https://github.com/gohilla/cryptography.dart
description: Chacha20 symmetric stream cipher.

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  cryptography: any

dev_dependencies:
  pedantic: ^1.0.0
